# Generated by Django 3.1.1 on 2020-09-28 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200921_0812'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_taken', models.DateField(auto_created=True, auto_now=True)),
                ('start_time', models.DateTimeField()),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='choice',
            name='content',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
