# Generated by Django 3.1.1 on 2020-09-28 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200928_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='quiz',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='main.quiz'),
        ),
    ]
