# Generated by Django 3.1.1 on 2020-10-01 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_assessment_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
