# Generated by Django 3.1.1 on 2020-10-01 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201001_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='start_time',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
