# Generated by Django 3.1.1 on 2020-10-01 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20201001_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='start_time',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
    ]
