# Generated by Django 3.1.1 on 2020-10-01 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20201001_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='quiz',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.quiz'),
        ),
    ]
